[build]
  command = "npm ci && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"

# Netlify Functions
[functions]
  directory = "netlify/functions"

# Variáveis de ambiente (configure também no painel da Netlify)
[build.environment]
  SMTP_HOST = "smtp.gmail.com"
  SMTP_PORT = "587"
  SMTP_FROM_EMAIL = "seu-email@gmail.com"
